### PR TITLE
rely on env variable to fix race condition with workspace file

### PR DESCRIPTION
**Pull request by chasebolt**
this fixes 1 of 2 concurrency issues defined in #17

### CODE REVIEW

**Comment by naorlivne** [comment]
Hi @chasebolt 

I don't see how will this resolve the race condition, it will still happen as the envvar might still be changed at the exact same time as the file version of it might change

**Comment by chasebolt** [comment]
you are right. i must not be running into the race condition because of how much faster it is now. im not familiar with python and was expecting each execution to be siloed.

**Comment by chasebolt** [comment]
for now, i still propose this improvement as it removes two calls to terraform with no drawback that i am able to discern atm.

**Comment by naorlivne** [comment]
Reading up on it I found 2 mentions in terraform git that would be a blocker for this change:

- https://github.com/hashicorp/terraform/issues/15874#issuecomment-324067433
- https://github.com/hashicorp/terraform/issues/15874#issuecomment-375447707

Basically the envvar TF_WORKSPACE only does select on preexisting workspaces but there are some backends that also use it to do create (which backends being what case is undocumented), I'm guessing that the backend your using must be one of those that also does create then but as I intend Terraformize to be generic it should cover all backends that support multiple workspaces.

**Comment by chasebolt** [comment]
FWIW those comments are from 2017 and 2018.

> At the moment the intent is that workspace creation is an explicit action since it's often undesirable that e.g. a typo would lead to implicitly creating a new workspace.

this doesnt really apply in the case of using this API. you are creating workspaces regardless without user confirmation.

> ... you can continue to rely on the implicit behavior of some of the backends for the foreseeable future.

this applies to both remote and local backend storage

**Comment by naorlivne** [comment]
> FWIW those comments are from 2017 and 2018.
> 
> > At the moment the intent is that workspace creation is an explicit action since it's often undesirable that e.g. a typo would lead to implicitly creating a new workspace.
> 
> this doesnt really apply in the case of using this API. you are creating workspaces regardless without user confirmation.
> 
> > ... you can continue to rely on the implicit behavior **of some of the backends** for the foreseeable future.
> 
> this applies to both remote and local backend storage

Not all remote backends, I'm with you with agreeing that it's most likely most of the backends that are covered but as there is no way for us to know which backend is covered by it & which isn't (let alone what happens when other backends will be added in the future) & this needs to cover all use cases I rather we stick with the safe file based approach, even if it's an extra API call to terraform

**Pull request closed without merging**
